package errors

const (
	ITEM_NOT_FOUND   = "ITEM_NOT_FOUND"
	INTERNAL_ERROR   = "INTERNAL_ERROR"
	UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
	DUPLICATED_ERROR = "DUPLICATED_ERROR"
	VALIDATION_ERROR = "VALIDATION_ERROR"
	UNAUTHORIZED     = "UNAUTHORIZED"
	DUPLICATE_ENTRY  = "DUPLICATE_ENTRY"
	BAD_REQUEST      = "BAD_REQUEST"
	FOREIGN_KEY_CONSTRAINT_ERROR
	INVALID_INPUT       = "INVALID_INPUT"
	FORBIDDEN           = "FORBIDDEN"
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
	INSUFFICIENT_STOCK  = "INSUFFICIENT_STOCK"
	INVALID_PRICE       = "INVALID_PRICE"
	VERSION_CONFLICT    = "VERSION_CONFLICT"
	PROCESSING_FAILED   = "PROCESSING_FAILED"
	PROCESSING_TIMEOUT  = "PROCESSING_TIMEOUT"
)
