package errors

const (
	ITEM_NOT_FOUND   = "ITEM_NOT_FOUND"
	INTERNAL_ERROR   = "INTERNAL_ERROR"
	UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
	DUPLICATED_ERROR = "DUPLICATED_ERROR"
	VALIDATION_ERROR = "VALIDATION_ERROR"
	UNAUTHORIZED     = "UNAUTHORIZED"
	DUPLICATE_ENTRY  = "DUPLICATE_ENTRY"
	BAD_REQUEST      = "BAD_REQUEST"
	FOREIGN_KEY_CONSTRAINT_ERROR
)
